
services:
  evolution-api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.1.1
    restart: always
    ports:
      - "3000:8080"
    env_file:
      - .env
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - postgres  # Aguarda que o PostgreSQL inicie primeiro

  postgres:
    image: postgres:13  # Usa uma imagem oficial do PostgreSQL
    restart: always
    environment:
      POSTGRES_USER: myuser         # Nome do utilizador do PostgreSQL
      POSTGRES_PASSWORD: mypassword # Palavra-passe do PostgreSQL
      POSTGRES_DB: mydatabase       # Nome da base de dados

    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência dos dados

  redis:
    image: redis:alpine
    restart: always

volumes:
  evolution_instances:
  postgres_data:
